// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQndedb-PSdzHTyNJdrktICtb1QoetT4',
    appId: '1:906709666761:web:9717c9cc0abf6cfaf73618',
    messagingSenderId: '906709666761',
    projectId: 'pedro-4f022',
    authDomain: 'pedro-4f022.firebaseapp.com',
    storageBucket: 'pedro-4f022.appspot.com',
    measurementId: 'G-G1D78W5JP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2TIEyeFjr44pwn-vhzPgVecJ8rJgwlY',
    appId: '1:906709666761:android:7300366e225488d9f73618',
    messagingSenderId: '906709666761',
    projectId: 'pedro-4f022',
    storageBucket: 'pedro-4f022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzKE4kokoXJDX0M5YejhyVAi6phH_MW7E',
    appId: '1:906709666761:ios:512acbc3ed902d2ef73618',
    messagingSenderId: '906709666761',
    projectId: 'pedro-4f022',
    storageBucket: 'pedro-4f022.appspot.com',
    iosClientId: '906709666761-ehhamm8sed1oqpr61u0dp3fjjh7ajo61.apps.googleusercontent.com',
    iosBundleId: 'com.example.iosfbaseapp',
  );
}
